name: "All tests"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  backend_tests:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.9

      - name: "Lint and test backend"
        run: "make lint-backend test-backend"

  frontend_tests:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup Node"
        uses: "actions/setup-node@v2"
        with:
          node-version: 14

      - name: "Lint and test frontend"
        run: "make lint-frontend test-frontend"

  e2e_tests:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.9

      - name: "Setup Node"
        uses: "actions/setup-node@v2.1.2"
        with:
          node-version: 14

      - name: "Run tests"
        run: "make test-e2e"
        continue-on-error: true

      - name: "Upload test results"
        uses: "actions/upload-artifact@v2"
        with:
          name: "shots"
          path: "e2e-tests/shots"
