name: "Build"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.9

      - name: "Setup Node"
        uses: "actions/setup-node@v2"
        with:
          node-version: 14

      - name: "Build and create archive"
        env:
          PRESTIGE_FRONTEND_ROLLBAR_TOKEN: ${{ secrets.PRESTIGE_FRONTEND_ROLLBAR_TOKEN }}
        run: |
          make build-all

      - name: "Upload to S3"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
          AWS_DEFAULT_OUTPUT: json
        run: |
          make upload-package
