name: "Build"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.9

      - name: "Setup Node"
        uses: "actions/setup-node@v2"
        with:
          node-version: 14

      - name: "Build and create archive"
        run: |
          make build-all

      - name: "Upload package to _main_ server"
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          mkdir ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/private_key
          echo "$SSH_CONFIG" > ~/.ssh/config
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/*
          scp package.tar.gz main:prestige-packages/package-"$(date +%Y-%m-%d-%H-%M-%S)".tar.gz
          rm -rf ~/.ssh

      - name: "Upload package artifact"
        uses: "actions/upload-artifact@v2"
        with:
          name: package
          path: package.tar.gz
