name: "Build"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.9

      - name: "Setup Node"
        uses: "actions/setup-node@v2"
        with:
          node-version: 14

      - name: "Create Archive"
        run: |
          make build-all

      - name: "Upload package artifact"
        uses: "actions/upload-artifact@v2"
        with:
          name: package
          path: package.tar.gz
