name: "Build"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.9

      - name: "Setup Node"
        uses: "actions/setup-node@v2"
        with:
          node-version: 14

      - name: "Build and create archive"
        run: |
          make build-all

      - name: "Upload to S3"
        env:
          AWS_CREDS: ${{ secrets.AWS_CREDS }}
        run: |
          echo "$AWS_CREDS" > ~/.aws/credentials
          make upload-package
